export const SUBSCRIPTION_PLANS = {
  FREE: {
    name: 'Free',
    price: 0,
    maxSavedPlans: 1,
    maxRecipes: 20,
    features: ['1 saved meal plan', 'Access to 20 recipes', 'Basic grocery list'],
    aiGeneration: false,
    pdfExport: false,
    macroTracking: false,
  },
  PRO: {
    name: 'Pro',
    price: 9.99,
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRO_PRICE_ID,
    maxSavedPlans: Infinity,
    maxRecipes: Infinity,
    features: ['Unlimited plans', 'Full recipe library', 'AI meal generation', 'PDF export', 'Macro tracking'],
    aiGeneration: true,
    pdfExport: true,
    macroTracking: true,
  },
  FAMILY: {
    name: 'Family',
    price: 14.99,
    priceId: process.env.NEXT_PUBLIC_STRIPE_FAMILY_PRICE_ID,
    maxSavedPlans: Infinity,
    maxRecipes: Infinity,
    maxProfiles: 6,
    features: ['Up to 6 dietary profiles', 'Shared grocery list', 'Multi-person servings', 'All Pro features'],
    aiGeneration: true,
    pdfExport: true,
    macroTracking: true,
  },
} as const
